### ISSUE TITLE
The datasets can`t be fetched.

### ISSUE THREAD

**Issue by ZipengFeng** [autonomousvision/shape_as_points#1]
Hello,  I want to download the demo data，but falied to establish SSL connection.
Could you please upload a copy to GoogleDrive at the same time?  
Thanks！

```
wget https://s3.eu-central-1.amazonaws.com/avg-projects/shape_as_points/data/demo.zip

--2021-11-10 10:33:21--  https://s3.eu-central-1.amazonaws.com/avg-projects/shape_as_points/data/demo.zip
Proxy tunneling failed: Bad GatewayUnable to establish SSL connection.
```

**Comment by pengsongyou** [comment]
Hi @ZipengFeng, this is strange because it works from my side. Moreover, even if you simply copy the [link](https://s3.eu-central-1.amazonaws.com/avg-projects/shape_as_points/data/demo.zip) without wget and open it in your browser, you should be able to download.

Seems like you are using some kind of proxy server. I would suggest that you use wget without proxy.

Best,
Songyou

**Comment by ZipengFeng** [comment]
> Hi @ZipengFeng, this is strange because it works from my side. Moreover, even if you simply copy the [link](https://s3.eu-central-1.amazonaws.com/avg-projects/shape_as_points/data/demo.zip) without wget and open it in your browser, you should be able to download.
> 
> Seems like you are using some kind of proxy server. I would suggest that you use wget without proxy.
> 
> Best, Songyou

**Comment by ZipengFeng** [comment]
I switched the network and it works.  Thank you very much.
