### ISSUE TITLE
Optimization-based vs. Learning-based results

### ISSUE THREAD

**Issue by eliahuhorwitz** [autonomousvision/shape_as_points#2]
Hey,
Thank you for publishing the code and congratulations on getting the NiPS oral!
Could you please provide some comparison of the Optimization-based vs. Learning-based results or at least provide some insight into what works better under what circumstances. 
(I looked through the paper and SM and couldn't find this, but if it exists and I've missed it, could you please point me in the right direction?)

Thanks,
Eliahu

**Comment by pengsongyou** [comment]
Hi @eliahuhorwitz,

Thanks for your words and interest in our work! As for your question, I will answer it as follows.

For the optimization-based pipeline, there is no network at all so no learning process is involved. This application is used to show the ability to reconstruct a wild range of shapes (as shown in the paper, we show results on 3 different datasets ranging from synthetic to real-world scans). Nevertheless, since no data prior is utilized, the optimization-based pipeline cannot handle very noisy point clouds or those with a large number of outliers. This is true for all optimization-based baselines as well. Also the reconstruction won't be good enough if the number of input points is small. Therefore, we further leverage the differentiability of our Poisson solver in learning the network parameters, which is the learning-based pipeline. In this way, we can train a network to handle very noisy inputs with outliers and the input number of points can be small. However, the learning-based pipeline has difficulty on generalizing to shapes out of training distribution, so it is less flexible than the optimization-based pipeline.

Hope this helps.

Best,
Songyou
